In [1]:
import numpy as np

In [2]:
# 1-Dimentional Array

myarray=np.array([1,2,3,4,5])

print(myarray)

print("1-Dimentional Array")

[1 2 3 4 5]
1-Dimentional Array


In [3]:
type(myarray)

numpy.ndarray

In [4]:
# 2-D array

myarray2=np.array([[1,2,3],[4,5,6]])
print(myarray2)

print("2 - D array")


[[1 2 3]
 [4 5 6]]
2 - D array


In [5]:
type(myarray2)

numpy.ndarray

In [6]:
# used zeros() function.

myarray3=np.zeros((2,3))
myarray3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# used ones() functions.

myarray4=np.ones((3,3))
myarray4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# used Identity() functions.

myarray5=np.identity(5)
myarray5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
# used arange() function to generate a array 

myarray6=np.arange(10)
myarray6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# how to get 5 to 15 number with the help of arange() function.

myarray7=np.arange(5,16)
myarray7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
# it is similar to range() in python.
# arange(starting values,last values,step values)

myarray8=np.arange(1,20,3)
myarray8

array([ 1,  4,  7, 10, 13, 16, 19])

In [12]:
# used linspace(lower range, upper range , jump) used 3 parameters

myarray9=np.linspace(10,20,10)
myarray9


array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [13]:
# used copy() functions

myarray10=myarray9.copy()
myarray10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

## some important attributes and properties. 

In [14]:
# 1.shape
# 2.ndim
# 3.size
# 4.itemsize
# 5.Dtype
# 6.astype()

In [15]:
# used shape() attributes

myarray.shape

(5,)

In [16]:
myarray2.shape

(2, 3)

In [17]:
 # used ndim (dimentional ) matrix
    
myarray.ndim

1

In [18]:
myarray2.ndim

2

In [19]:
# create 3-D array 

myarray11=np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
myarray11

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
myarray11.ndim

3

In [21]:
myarray11.shape

(2, 2, 2)

In [22]:
myarray.size

5

In [23]:
myarray.dtype

dtype('int32')

In [24]:
myarray9.size

10

In [25]:
myarray9.dtype

dtype('float64')

## Compare Numpy & List 

### numpy is faster to campare to list

In [26]:
# example 

list=range(100)
array1=np.arange(100)

In [27]:
import sys

In [28]:
print(sys.getsizeof(85)*len(list))

2800


In [29]:
print(array1.itemsize*array1.size)

400


### indexing , slicing and iteration on numpy

In [30]:
# used reshape() functio

array2=np.arange(24)
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
# used reshape() function


array2=np.arange(24).reshape(6,4)
array2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
# we get 3rd row

array2[2]

array([ 8,  9, 10, 11])

In [33]:
# how to get 3rd column 

array2[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [34]:
array2[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [35]:
array2[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [36]:
# Apply iterations

for i in array2:
    print(i)


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [37]:
for i in np.nditer(array2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


### Basic Arthematic operations of numpy

In [38]:
aray1=np.array([1,2,3,4,5,6])
aray2=np.array([4,5,6,7,8,9])

In [39]:
aray1+aray2

array([ 5,  7,  9, 11, 13, 15])

In [40]:
aray1*aray2

array([ 4, 10, 18, 28, 40, 54])

In [41]:
aray2*3


array([12, 15, 18, 21, 24, 27])

In [42]:
aray1>1

array([False,  True,  True,  True,  True,  True])

In [43]:
aray3=np.arange(6).reshape(2,3)
aray4=np.arange(6,12).reshape(3,2)

In [44]:
aray3.dot(aray4)

array([[ 28,  31],
       [100, 112]])

In [45]:
aray4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [46]:
aray4.max()

11

In [47]:
aray4.min()

6

In [48]:
aray4.min(axis=0)

array([6, 7])

In [49]:
aray4.min(axis=1)

array([ 6,  8, 10])

In [50]:
aray4.sum()

51

In [51]:
aray4.sum(axis=1)

array([13, 17, 21])

In [52]:
aray4.std()

1.707825127659933

In [53]:
aray5=np.arange(50)
aray5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [54]:
np.median(aray5)

24.5

### Reshaping Numpy arrays.

In [55]:
# ravel()
# resape()
# Transpose()
# 

In [56]:
aray4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [57]:
aray4.ndim

2

In [58]:
aray4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [59]:
aray4.reshape(2,3)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
aray5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [61]:
aray5.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [62]:
aray4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [63]:
aray6=np.arange(24).reshape(6,4)
aray6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
# fancing indexing.

aray6[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [65]:
arr=np.random.rand(100)
arr

array([0.27898074, 0.39088517, 0.71551791, 0.69261859, 0.42133472,
       0.78333356, 0.49541769, 0.92428505, 0.59368925, 0.88664379,
       0.02751424, 0.54870068, 0.07947137, 0.34519518, 0.64463683,
       0.51078513, 0.61011891, 0.74586839, 0.04869774, 0.81162314,
       0.05474713, 0.11343729, 0.29280919, 0.34038567, 0.53427285,
       0.18752461, 0.88924215, 0.99030243, 0.33917257, 0.20844418,
       0.38820541, 0.34892556, 0.33848183, 0.98291591, 0.80396035,
       0.91877991, 0.91464082, 0.70575788, 0.80132449, 0.13924208,
       0.66591078, 0.3143397 , 0.9668544 , 0.18914961, 0.70719355,
       0.63322175, 0.00651289, 0.60891328, 0.50742691, 0.85828412,
       0.05746859, 0.32483689, 0.83769996, 0.93768625, 0.79752354,
       0.41116059, 0.33063479, 0.67564902, 0.65663048, 0.57948724,
       0.84768819, 0.62360568, 0.51028854, 0.72405524, 0.18700421,
       0.53887607, 0.83703193, 0.16759449, 0.52295903, 0.87762241,
       0.71403811, 0.13548885, 0.68175464, 0.03184868, 0.80177